apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gateman-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateman-server
  minReplicas: 1 
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
