apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gateman-server
  name: gateman-server
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gateman-server
  type: LoadBalancer
status:
  loadBalancer: {}
