name: gateman-staging-deployment

env:
  resourceGroup: "gateman-prod"
  kubernetesVersion: "1.19.6"
  name: 'gateman-prod'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

# Jobs section defines the actual work to be done
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Login
      uses: Azure/login@v2.2.0
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Azure CLI Action
      uses: Azure/cli@v2.1.0
      with:
        # Specify the script here
        inlineScript: az aks create -g ${{ env.resourceGroup }} -n ${{ env.name }} --kubernetes-version ${{ env.kubernetesVersion }} --generate-ssh-keys
              
